operator-helm:
  fullnameOverride: sanjagh

  image:
    registry: ghcr.io
    repository: mohammadne/sanjagh
    pullPolicy: Always
    tag: "v0.1.2-rc5"

  manager:
    rules:
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
      - apiGroups: ["apps.mohammadne.me"]
        resources: ["executers"]
        verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
      - apiGroups: ["apps.mohammadne.me"]
        resources: ["executers/status"]
        verbs: ["get", "update", "patch"]
      - apiGroups: ["apps.mohammadne.me"]
        resources: ["executers/finalizers"]
        verbs: ["update"]

  webhook:
    replicas: 1

    mutation:
      enabled: false

    validation:
      enabled: true
      path: "/validation"
      rules:
        - operations: ["CREATE", "UPDATE"]
          apiGroups: ["apps.mohammadne.me"]
          apiVersions: ["v1alpha1"]
          resources: ["executers"]

  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    selector: {}

  config:
    enabled: true
    mountPath: /tmp/operator
    values:
      webhook:
        server:
          tls:
            certificate: /tmp/secrets/tls.crt
            private_key: /tmp/secrets/tls.key
