---
- name: "Get list of kind clusters"
  command: kind get clusters
  register: existing_clusters
  changed_when: false

- name: "Define kindconfig path variable"
  set_fact:
    kindconfig_path: "/tmp/kindconfig.yaml"

- name: "Create kindconfig file from template"
  template:
    src: kindconfig.yaml.j2
    dest: "{{ kindconfig_path }}"

- name: "Create kind cluster based on kindconfig file"
  shell: "kind create cluster --name {{ k8s_cluster_name }} --image {{ kind_kubernetes_image }} --config {{ kindconfig_path }} --kubeconfig $HOME/.kube/kind-{{ k8s_cluster_name }}.conf"
  when: k8s_cluster_name not in existing_clusters.stdout_lines

- name: Delete generate kindconfig file
  file:
    path: /tmp/kindconfig.yaml
    state: absent
